{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name" . }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: {{ include "app.fqdn" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "app.name" . }}
            port:
              number: 80
  tls:
  - hosts:
    - {{ include "app.fqdn" . }}
    secretName: {{ include "app.secretName" . }}
{{- end -}} 